spring.application.name=chessgame

server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:46836/railway
spring.datasource.username=root
spring.datasource.password=UgloqZarnpFoSIBMEbFKOMrYGrbcKjov

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
