spring.application.name=chessgame

server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:49111/railway
spring.datasource.username=root
spring.datasource.password=hlgAXPjLFmnhlyqeEetoVpUHpVEzFYQb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
